<Project Sdk="Aspire.AppHost.Sdk/13.4.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>c4741def-89d5-447e-af79-e43ded7574ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
    <PackageReference Include="Keycloak.AuthServices.Aspire.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CatalogService/CatalogService.csproj" />
    <ProjectReference Include="../OrderService/OrderService.csproj" />
    <ProjectReference Include="../PaymentService/PaymentService.csproj" />
    <ProjectReference Include="../ShippingService/ShippingService.csproj" />
    <ProjectReference Include="../NotificationService/NotificationService.csproj" />
    <ProjectReference Include="../Storefront/Storefront.csproj" />
    <ProjectReference Include="../SellerPortal/SellerPortal.csproj" />
  </ItemGroup>

</Project>
